begin;

create table if not exists public.candidates (
  id bigint generated by default as identity primary key,

  -- Generated by the application, for example CBJ-20261001-2CA4.
  candidate_id text not null unique
    check (candidate_id ~ '^CBJ-[0-9]{8}-[A-F0-9]{4}$'),

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  -- Admin Dashboard workflow.
  status text not null default 'new'
    check (status in (
      'new', 'contacted', 'interview', 'shortlisted',
      'placed', 'rejected', 'on_hold'
    )),
  score integer not null check (score between 0 and 100),
  priority text not null check (priority in ('high', 'medium', 'low')),
  score_breakdown jsonb not null
    check (
      jsonb_typeof(score_breakdown) = 'object'
      and score_breakdown ?& array[
        'job_intent',
        'start_timing',
        'residence_work_feasibility',
        'experience_skills',
        'japanese_level',
        'english_other',
        'cv_readiness'
      ]
    ),

  -- Step 1: contact and location.
  full_name text not null check (btrim(full_name) <> ''),
  email text not null check (btrim(email) <> '' and position('@' in email) > 1),
  phone text,
  nationality text,
  current_country text not null check (btrim(current_country) <> ''),

  -- Step 2: work feasibility.
  residence_status text not null
    check (residence_status in (
      'permanent_resident', 'spouse', 'work_visa', 'student',
      'dependent', 'specified_skilled', 'outside_japan', 'other'
    )),
  work_permission text not null
    check (work_permission in ('yes', 'needs_support', 'no')),
  desired_jobs text not null check (btrim(desired_jobs) <> ''),
  job_intent text not null
    check (job_intent in ('actively_looking', 'open_to_offers', 'researching')),

  -- Step 3: skills and readiness.
  japanese_level text not null
    check (japanese_level in ('native', 'n1', 'n2', 'n3', 'n4', 'n5', 'none')),
  english_level text not null
    check (english_level in ('native', 'business', 'conversational', 'basic', 'none')),
  other_languages text,
  years_experience text not null
    check (years_experience in ('0', '1-2', '3-5', '6+')),
  skills text not null check (btrim(skills) <> ''),
  start_timing text not null
    check (start_timing in (
      'immediately', 'within_1_month', 'within_3_months',
      'within_6_months', 'later'
    )),
  cv_readiness text not null
    check (cv_readiness in ('ready', 'needs_update', 'need_help')),

  -- Step 4: interview and consent. interview_datetime intentionally stores
  -- the candidate's local datetime; timezone identifies how to interpret it.
  interview_datetime text not null check (btrim(interview_datetime) <> ''),
  timezone text not null check (btrim(timezone) <> ''),
  notes text,
  privacy_consent boolean not null check (privacy_consent is true),
  contact_consent boolean not null default false
);

comment on table public.candidates is
  'Career Bridge Japan MVP v2 candidate applications and admin workflow';
comment on column public.candidates.interview_datetime is
  'Candidate preferred local datetime from an HTML datetime-local input';
comment on column public.candidates.timezone is
  'Timezone used to interpret interview_datetime';
comment on column public.candidates.score_breakdown is
  'Points awarded for each configurable scoring category';

create or replace function public.set_candidates_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists candidates_set_updated_at on public.candidates;
create trigger candidates_set_updated_at
before update on public.candidates
for each row
execute function public.set_candidates_updated_at();

create index if not exists candidates_created_at_idx
  on public.candidates (created_at desc);
create index if not exists candidates_priority_status_created_idx
  on public.candidates (priority, status, created_at desc);
create index if not exists candidates_status_created_idx
  on public.candidates (status, created_at desc);

alter table public.candidates enable row level security;

-- The MVP server uses the Supabase service role, which bypasses RLS.
-- No anon/authenticated policies are created, so browsers cannot access rows
-- directly even if the public project URL is known.
revoke all on table public.candidates from anon, authenticated;
revoke all on sequence public.candidates_id_seq from anon, authenticated;

commit;
